// Core/mirrorSync.test.js — CR-I2 (v2.74.926): the classic content script can't import ESM, so the repo
// hand-mirrors safety-relevant constants/algorithms from Core into ContentScripts/contentScript.js. The
// only sync mechanism was a comment — and the NEWEST mirror (interactionCapture) had already drifted
// (missing focusout/blur mapping + the password-input role rule) before this test existed. These tests
// read BOTH sources as TEXT and assert the mirrors agree, turning silent drift into a red test.
//
// Mirror inventory pinned here:
//   1. DESTRUCTIVE_LABEL        Core/bind.js          ↔ contentScript (EX-1 poke veto)   — byte-equal regex
//   2. TRIAL_SELECT_FIRST       Core/trialSynth.js    ↔ contentScript handleSelect       — equal literal
//   3. isStableIdent            Core/selectorStability ↔ contentScript                    — equal body
//   4. isAutoGeneratedClass     Core/selectorStability ↔ contentScript                    — equal body
//   5. classifySelectorTier     Core/selectorStability ↔ contentScript _classifySelectorTier — equal body
//   6. selectMostDurableUnique  Core/selectorStability ↔ contentScript _mostDurableUnique — equal body (param renamed)
//   7. interactionCapture       Core/interactionCapture ↔ contentScript _IM_*             — documented subset

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel) => readFileSync(path.join(ROOT, rel), 'utf8');

const CS = read('ContentScripts/contentScript.js');
const BIND = read('Core/bind.js');
const TRIAL = read('Core/trialSynth.js');
const STAB = read('Core/selectorStability.js');
const ICAP = read('Core/interactionCapture.js');

// Extract a regex literal assigned to `const NAME = /.../flags;` (first occurrence).
function regexLiteral(src, name, file) {
  const m = src.match(new RegExp(`const ${name}\\s*=\\s*(\\/(?:[^\\/\\\\\\n]|\\\\.)+\\/[a-z]*)`));
  assert.ok(m, `${file}: const ${name} = /…/ not found`);
  return m[1];
}

// Extract a function's BODY text (between its outer braces) by brace matching from `function NAME(`.
function fnBody(src, name, file) {
  const sig = src.indexOf(`function ${name}(`);
  assert.ok(sig >= 0, `${file}: function ${name}( not found`);
  const open = src.indexOf('{', sig);
  let depth = 0;
  for (let i = open; i < src.length; i++) {
    const c = src[i];
    if (c === '{') depth++;
    else if (c === '}') { depth--; if (depth === 0) return src.slice(open + 1, i); }
  }
  assert.fail(`${file}: unbalanced braces in ${name}`);
}
// First parameter name of `function NAME(p...)`.
function fnParam(src, name) {
  const m = src.match(new RegExp(`function ${name}\\(([^),\\s]+)`));
  return m ? m[1] : null;
}
// Code equality is the contract — comments may legitimately differ between the canonical and the mirror.
const normalize = (s) => s.replace(/\/\/[^\n]*/g, '').replace(/\/\*[\s\S]*?\*\//g, '').replace(/\s+/g, ' ').trim();

describe('mirrorSync — content-script mirrors agree with their Core canonicals (CR-I2)', () => {
  it('1. DESTRUCTIVE_LABEL is byte-identical (SAFETY lexicon: bind veto ↔ poke-sweep veto)', () => {
    assert.equal(regexLiteral(CS, 'DESTRUCTIVE_LABEL', 'contentScript'), regexLiteral(BIND, 'DESTRUCTIVE_LABEL', 'bind.js'));
  });

  it('2. TRIAL_SELECT_FIRST sentinel literal matches', () => {
    const core = TRIAL.match(/TRIAL_SELECT_FIRST\s*=\s*'([^']+)'/);
    assert.ok(core, 'trialSynth: TRIAL_SELECT_FIRST export not found');
    assert.ok(CS.includes(`'${core[1]}'`), `contentScript no longer contains the sentinel '${core[1]}'`);
  });

  it('3-5. isStableIdent / isAutoGeneratedClass / classifySelectorTier bodies are identical', () => {
    // CS names align with Core's since the .926 re-sync — REQUIRED for classifySelectorTier, whose Core
    // name is called inside selectMostDurableUnique's body (the bcp diff review caught the underscore
    // variant making that sibling call unresolvable in the content script).
    for (const [coreName, csName] of [
      ['isStableIdent', 'isStableIdent'],
      ['isAutoGeneratedClass', 'isAutoGeneratedClass'],
      ['classifySelectorTier', 'classifySelectorTier'],
    ]) {
      assert.equal(
        normalize(fnBody(CS, csName, 'contentScript')),
        normalize(fnBody(STAB, coreName, 'selectorStability')),
        `${csName} drifted from Core ${coreName}`,
      );
    }
  });

  it('6. selectMostDurableUnique body identical modulo the renamed parameter', () => {
    const coreParam = fnParam(STAB, 'selectMostDurableUnique');
    const csParam = fnParam(CS, '_mostDurableUnique');
    assert.ok(coreParam && csParam, 'parameter names not found');
    const sub = (body, from) => normalize(body).replace(new RegExp(`\\b${from}\\b`, 'g'), '__P__');
    assert.equal(
      sub(fnBody(CS, '_mostDurableUnique', 'contentScript'), csParam),
      sub(fnBody(STAB, 'selectMostDurableUnique', 'selectorStability'), coreParam),
      '_mostDurableUnique drifted from Core selectMostDurableUnique',
    );
  });

  it('7a. _IM_EVENT_KIND is exactly Core DOM_EVENT_KIND minus the documented focusout omission', () => {
    const entries = (src, name) => {
      const m = src.match(new RegExp(`${name}\\s*=\\s*(?:Object\\.freeze\\()?\\{([^}]+)\\}`));
      assert.ok(m, `${name} object literal not found`);
      const map = {};
      for (const pair of m[1].split(',')) {
        const kv = pair.match(/([a-zA-Z]+)\s*:\s*'([a-z]+)'/);
        if (kv) map[kv[1]] = kv[2];
      }
      return map;
    };
    const core = entries(ICAP, 'DOM_EVENT_KIND');
    const cs = entries(CS, 'const _IM_EVENT_KIND');
    for (const [k, v] of Object.entries(cs)) assert.equal(core[k], v, `CS maps ${k}→${v} but Core maps ${k}→${core[k]}`);
    const omitted = Object.keys(core).filter((k) => !(k in cs));
    assert.deepEqual(omitted, ['focusout'], `documented omission is exactly focusout, got: ${omitted.join(',')}`);
  });

  it('7b. the three sensitivity rules exist on BOTH sides (password type, autocomplete set, password-input role)', () => {
    const acCore = ICAP.match(/\\b\(one-time-code[^/]+\)\\b/);
    const acCs = CS.match(/\\b\(one-time-code[^/]+\)\\b/);
    assert.ok(acCore && acCs, 'autocomplete sensitivity regex missing on a side');
    assert.equal(acCs[0], acCore[0], 'autocomplete sensitivity set drifted');
    for (const [src, file] of [[ICAP, 'Core/interactionCapture'], [CS, 'contentScript']]) {
      assert.ok(src.includes(`'password'`), `${file}: password type rule missing`);
      assert.ok(src.includes(`'password-input'`), `${file}: password-input role rule missing`);
    }
  });
});
