// Core/selectorStability.test.js — selector durability classification + most-durable-unique choice (GA-2).
// @version 2.74.839

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { classifySelectorTier, selectMostDurableUnique, isAutoGeneratedClass } from './selectorStability.js';

describe('selectorStability — classifySelectorTier', () => {
  it('rates by the strongest discriminator (lower = more durable)', () => {
    assert.equal(classifySelectorTier('#main'), 1, 'stable #id → 1');
    assert.equal(classifySelectorTier('[data-testid="job"]'), 2, 'test marker → 2');
    assert.equal(classifySelectorTier('[aria-label="Search"]'), 3, 'aria/name/role → 3');
    assert.equal(classifySelectorTier('div.jobCard'), 4, 'one stable class → 4');
    assert.equal(classifySelectorTier('div.jobCard.featured'), 5, 'multi stable class → 5');
    assert.equal(classifySelectorTier('div > div:nth-of-type(3)'), 6, 'purely structural → 6');
    assert.equal(classifySelectorTier(''), 99, 'empty → 99');
  });

  it('a strong anchor anywhere in the path wins even with a brittle nth elsewhere', () => {
    // The whole-selector tier is the STRONGEST discriminator present — an #id ancestor lifts the brittle leaf.
    assert.equal(classifySelectorTier('#main > div:nth-of-type(3)'), 1);
  });
});

describe('selectorStability — selectMostDurableUnique (GA-2)', () => {
  it('prefers the lower tier (a parent #id beats a bare structural prefix)', () => {
    const r = selectMostDurableUnique(['div > div:nth-of-type(3)', '#main > div:nth-of-type(3)']);
    assert.equal(r, '#main > div:nth-of-type(3)', 'tier 1 beats tier 6');
  });

  it('breaks ties on the SHORTEST (the original shortest-unique survives among same-tier candidates)', () => {
    const r = selectMostDurableUnique(['div.jobCard', 'section > div.jobCard']);
    assert.equal(r, 'div.jobCard', 'both tier 4 → shortest wins (no needless deepening)');
  });

  it('is strictly non-regressive for an all-structural set: returns the shortest (= the original first-unique)', () => {
    const r = selectMostDurableUnique(['ul > li:nth-of-type(2)', 'div > ul > li:nth-of-type(2)', 'main > div > ul > li:nth-of-type(2)']);
    assert.equal(r, 'ul > li:nth-of-type(2)', 'no anchor found anywhere → keep the shortest');
  });

  it('picks an id over a class over structural', () => {
    assert.equal(selectMostDurableUnique(['div.jobCard', 'div', '#mainHeader']), '#mainHeader');
    assert.equal(selectMostDurableUnique(['div', 'div.jobCard']), 'div.jobCard', 'one stable class beats tag-only');
  });

  it('empty / invalid → empty string', () => {
    assert.equal(selectMostDurableUnique([]), '');
    assert.equal(selectMostDurableUnique(null), '');
    assert.equal(selectMostDurableUnique([null, 42, '']), '');
  });
});

// A couple of isAutoGeneratedClass anchors (the class filter both selector builders share).
describe('selectorStability — isAutoGeneratedClass', () => {
  it('flags per-instance hash-key classes, keeps semantic ones', () => {
    assert.equal(isAutoGeneratedClass('job_070d04fc4355bc03'), true, 'name_<hex> per-instance key');
    assert.equal(isAutoGeneratedClass('jobCard'), false, 'semantic class kept');
    assert.equal(isAutoGeneratedClass('is_active'), false, 'short BEM/state suffix kept');
  });
});
