// Core/selectorStability.js — SG-LM-1. THE canonical predicate for selector/identifier stability.
//
// One source of truth for "is this id/class a durable discriminator, or a machine-generated token that
// regenerates across builds/renders?" Previously this logic was duplicated (and drifting) in three
// places: ContentScripts/contentScript.js (`isStableIdent` + `isAutoGeneratedClass`) and
// Services/LandmarkProfile.js (`_isStableIdent` + `classifySelectorTier`). The LandmarkProfile copy had
// gone stale — its `classifySelectorTier` ranked CSS-module hashes like `button--af32y` as a *stable*
// class. This module is the authority; ESM consumers import it.
//
// NOTE: a classic content script can't `import`, so ContentScripts/contentScript.js keeps a VERBATIM
// MIRROR of `isStableIdent` / `isAutoGeneratedClass` with a "keep in sync" header. Any rule change lands
// here first, then is copied there. PURE — no DOM, no I/O.
//
// @module Core/selectorStability

/**
 * Is `s` a STABLE identifier — safe to use as a durable selector discriminator (#id, .class, [name])?
 * Rejects the machine-generated patterns that resolve uniquely at capture but break on the next render
 * or deploy. A false reject is cheap (the synthesizer falls through to the next, more-positional tier);
 * a false accept rots a saved selector.
 * @param {string} s  an id, class, or name token (no leading # / .)
 * @returns {boolean}
 */
export function isStableIdent(s) {
  if (!s || typeof s !== 'string') return false;
  if (s.length < 2) return false;
  if (/^\d+$/.test(s)) return false;                      // all numeric
  if (/__[A-Za-z0-9_-]{3,}$/.test(s)) return false;       // CSS-modules `foo__a1B2` suffix
  if (/^:r[0-9a-z]+:$/.test(s)) return false;             // React 18 useId: :r0:, :rb:, :rcd:
  if (/^_r\d/.test(s)) return false;                      // older React/Emotion underscore prefix
  if (/^css-[a-z0-9]{6,}$/.test(s)) return false;         // emotion-style hashes
  if (/[0-9]{4,}/.test(s)) return false;                  // long digit run
  if (/^[a-f0-9]{8,}$/i.test(s)) return false;            // hex-only run
  // Component-library auto ids with a SHORT counter the `[0-9]{4,}` rule misses (Fluent/Fabric
  // "FabricTextField-324", Radix, Headless UI, Chakra, …); plus a generic ComponentName-NNN counter.
  if (/^(fab|fluent|radix|headlessui|chakra|mantine|downshift|tippy|popper|floatingui|reach|reakit|react-?select|react-?aria)[a-z0-9_-]*\d/i.test(s)) return false;
  if (/[a-z][A-Z][A-Za-z]*-?\d{2,3}$/.test(s)) return false;   // ComponentName-324, fieldName12
  // Styled-components bare hash class: pure-alpha 5-10, mixed case, vowel density < 25%
  // (protects camelCase identifiers like `navItem`/`editBtn` which are ≥28% vowels).
  if (/^[a-zA-Z]{5,10}$/.test(s) && /[a-z]/.test(s) && /[A-Z]/.test(s)) {
    const vowels = (s.match(/[aeiouAEIOU]/g) ?? []).length;
    if (vowels / s.length < 0.25) return false;
  }
  // CSS-modules `name--hash` segment whose hash regenerates per build (Pixabay `button--af32y`).
  // Distinguished from a BEM modifier (`block--primary`, a word): a hash mixes letter+digit, mixes
  // upper+lower case, or is vowel-poor. Length 4-8 so short modifiers (`--lg`, `--xl`) are left alone.
  const seg = /--([A-Za-z0-9]{4,8})$/.exec(s);
  if (seg) {
    const h = seg[1];
    const mixedCase = /[a-z]/.test(h) && /[A-Z]/.test(h);
    const alnum = /\d/.test(h) && /[A-Za-z]/.test(h);
    const vowelPoor = ((h.match(/[aeiouAEIOU]/g) || []).length / h.length) < 0.25;
    if (mixedCase || alnum || vowelPoor) return false;
  }
  return true;
}

/**
 * Is `className` an auto-generated CSS-in-JS / CSS-modules class? Used by the structural-selector
 * builder to drop hash classes before they form a `tag.class` discriminator. Covers the framework
 * prefixes (Emotion `css-`/`e…`, styled-components `sc-`) plus the CSS-modules `name--hash` form.
 * @param {string} className
 * @returns {boolean}
 */
export function isAutoGeneratedClass(className) {
  if (!className) return false;
  if (/^css-[a-z0-9]{5,}$/i.test(className)) return true;   // emotion css-<hash>
  if (/^e[a-z0-9]{6,}$/i.test(className)) return true;      // emotion e<hash>
  if (/^sc-[a-z0-9]{4,}$/i.test(className)) return true;    // styled-components sc-<hash>
  if (/^ecydgvn[0-9]+$/i.test(className)) return true;      // observed generated prefix
  // v2.74.598 — CSS-modules `name--hash` (Pixabay `button--af32y`); same discriminator as isStableIdent
  // so the structural builder (computeUniqueSelector) and synthesizeSelector agree on hashed classes.
  const seg = /--([A-Za-z0-9]{4,8})$/.exec(className);
  if (seg) {
    const h = seg[1];
    const mixedCase = /[a-z]/.test(h) && /[A-Z]/.test(h);
    const alnum = /\d/.test(h) && /[A-Za-z]/.test(h);
    const vowelPoor = ((h.match(/[aeiouAEIOU]/g) || []).length / h.length) < 0.25;
    if (mixedCase || alnum || vowelPoor) return true;
  }
  // v2.74.706 — Per-instance KEY class `name_<hash>`: the suffix after the last underscore is a long hex
  // token (Indeed's per-card `job_070d04fc4355bc03`) or a letter+digit hash. These tag ONE instance (one
  // job card / one row) and regenerate per item, so they're fatal to a POSITIONAL read ("the first job"),
  // which must match the archetype shared by every card — not this card's key. Short BEM/state suffixes
  // (`col_2`, `is_active`, `step_1`, `grid_12`) are left alone (suffix < 8 chars, or no digit).
  const useg = /_([A-Za-z0-9]{8,})$/.exec(className);
  if (useg) {
    const h = useg[1];
    const hexKey   = /^[0-9a-f]+$/i.test(h);                    // pure hex ≥8 (070d04fc4355bc03)
    const alnumKey = /[A-Za-z]/.test(h) && /\d/.test(h);        // mixed letter+digit hash ≥8
    if (hexKey || alnumKey) return true;
  }
  return false;
}

/**
 * Classify a CSS selector by its strongest (most durable) discriminator. Lower tier = more stable.
 *   1 #id (stable) · 2 test markers · 3 aria-label/name/role · 4 single stable class · 5 multi-class ·
 *   6 structural/tag-only · 99 empty/unclassifiable.
 * @param {string} selector
 * @returns {number}
 */
export function classifySelectorTier(selector) {
  if (!selector || typeof selector !== 'string') return 99;
  const s = selector.trim();
  if (!s) return 99;
  const idMatch = s.match(/#([\w-]+)/);
  if (idMatch && isStableIdent(idMatch[1])) return 1;
  if (/\[\s*(data-test-id|data-testid|data-test|data-qa|data-cy)\b/i.test(s)) return 2;
  if (/\[\s*(aria-label|aria-labelledby|name|role)\b/i.test(s)) return 3;
  const classMatches = s.match(/\.[A-Za-z_][\w-]*/g) || [];
  const stableClasses = classMatches.filter(c => isStableIdent(c.slice(1)));
  if (stableClasses.length === 1) return 4;
  if (stableClasses.length >= 2) return 5;
  return 6;
}

/**
 * v2.74.839 (GA-2) — choose the most DURABLE selector from candidates that ALL uniquely resolve the SAME element
 * (e.g. each successively-deeper prefix of an ascending selector build). Picks the lowest classifySelectorTier (the
 * strongest discriminator), ties broken by shortest length (fewer ancestors ⇒ fewer things that can drift). PURE.
 * The selector builder uses this to avoid greedily returning a purely-structural shortest-unique (a bare
 * `div > div:nth-of-type(3)`, tier 6) when a one-level-deeper prefix gains a stable `#id`/class anchor.
 * @param {string[]} candidates
 * @returns {string} the most durable candidate, or '' for an empty/invalid set
 */
export function selectMostDurableUnique(candidates) {
  const list = (Array.isArray(candidates) ? candidates : []).filter((s) => typeof s === 'string' && s.trim());
  if (!list.length) return '';
  let best = list[0];
  let bestTier = classifySelectorTier(best);
  for (let i = 1; i < list.length; i++) {
    const t = classifySelectorTier(list[i]);
    if (t < bestTier || (t === bestTier && list[i].length < best.length)) { best = list[i]; bestTier = t; }
  }
  return best;
}
