// Core/selectorStability.test.js — selector durability classification + most-durable-unique choice (GA-2).

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { classifySelectorTier, selectMostDurableUnique, isAutoGeneratedClass, isStableIdent, selectorRelaxations } from './selectorStability.js';

describe('selectorStability — classifySelectorTier', () => {
  it('rates by the strongest discriminator (lower = more durable)', () => {
    assert.equal(classifySelectorTier('#main'), 1, 'stable #id → 1');
    assert.equal(classifySelectorTier('[data-testid="job"]'), 2, 'test marker → 2');
    assert.equal(classifySelectorTier('[aria-label="Search"]'), 3, 'aria/name/role → 3');
    assert.equal(classifySelectorTier('div.jobCard'), 4, 'one stable class → 4');
    assert.equal(classifySelectorTier('div.jobCard.featured'), 5, 'multi stable class → 5');
    assert.equal(classifySelectorTier('div > div:nth-of-type(3)'), 6, 'purely structural → 6');
    assert.equal(classifySelectorTier(''), 99, 'empty → 99');
  });

  it('a strong anchor anywhere in the path wins even with a brittle nth elsewhere', () => {
    // The whole-selector tier is the STRONGEST discriminator present — an #id ancestor lifts the brittle leaf.
    assert.equal(classifySelectorTier('#main > div:nth-of-type(3)'), 1);
  });
});

describe('selectorStability — selectMostDurableUnique (GA-2)', () => {
  it('prefers the lower tier (a parent #id beats a bare structural prefix)', () => {
    const r = selectMostDurableUnique(['div > div:nth-of-type(3)', '#main > div:nth-of-type(3)']);
    assert.equal(r, '#main > div:nth-of-type(3)', 'tier 1 beats tier 6');
  });

  it('breaks ties on the SHORTEST (the original shortest-unique survives among same-tier candidates)', () => {
    const r = selectMostDurableUnique(['div.jobCard', 'section > div.jobCard']);
    assert.equal(r, 'div.jobCard', 'both tier 4 → shortest wins (no needless deepening)');
  });

  it('is strictly non-regressive for an all-structural set: returns the shortest (= the original first-unique)', () => {
    const r = selectMostDurableUnique(['ul > li:nth-of-type(2)', 'div > ul > li:nth-of-type(2)', 'main > div > ul > li:nth-of-type(2)']);
    assert.equal(r, 'ul > li:nth-of-type(2)', 'no anchor found anywhere → keep the shortest');
  });

  it('picks an id over a class over structural', () => {
    assert.equal(selectMostDurableUnique(['div.jobCard', 'div', '#mainHeader']), '#mainHeader');
    assert.equal(selectMostDurableUnique(['div', 'div.jobCard']), 'div.jobCard', 'one stable class beats tag-only');
  });

  it('empty / invalid → empty string', () => {
    assert.equal(selectMostDurableUnique([]), '');
    assert.equal(selectMostDurableUnique(null), '');
    assert.equal(selectMostDurableUnique([null, 42, '']), '');
  });
});

// A couple of isAutoGeneratedClass anchors (the class filter both selector builders share).
describe('selectorStability — isAutoGeneratedClass', () => {
  it('flags per-instance hash-key classes, keeps semantic ones', () => {
    assert.equal(isAutoGeneratedClass('job_070d04fc4355bc03'), true, 'name_<hex> per-instance key');
    assert.equal(isAutoGeneratedClass('jobCard'), false, 'semantic class kept');
    assert.equal(isAutoGeneratedClass('is_active'), false, 'short BEM/state suffix kept');
  });
});

// ── selectorRelaxations (v2.74.1008) ────────────────────────────────────────────────────────────
// Replay-time relaxation for reads over dynamic lists. Documents the fix for the cross-Ground read
// break (findings 2026-06-13 21:54): a demonstrated read pinned to ONE Indeed job card matched 0
// elements on a fresh result set, killing the read step (and so the cross-Ground value hand-off).

// The exact selector the failing read stored: a single job card — per-posting key class job_<hex>,
// an Emotion hash, and per-render state/layout classes that a fresh card lacks.
const INDEED_BRITTLE =
  'div.cardOutline.tapItem.dd-privacy-allow.result.job_ee158ac0af90ece8.maybeSponsoredJob' +
  '.resultWithShelf.sponTapItem.desktop.hasSection.hasSection-rjpOnSerp.hasSection-extraTier' +
  '.recommendation-section.vjs-highlight.eu4oa1w0';

describe('selectorRelaxations — the Indeed read break (v2.74.1008)', () => {
  it('reaches the durable container `div.cardOutline.tapItem.dd-privacy-allow.result`', () => {
    const relaxed = selectorRelaxations(INDEED_BRITTLE);
    assert.ok(
      relaxed.includes('div.cardOutline.tapItem.dd-privacy-allow.result'),
      'the stable base (which matches every fresh job card) must be among the relaxations',
    );
  });

  it('first relaxation strips ONLY auto-generated classes (job_<hex> + emotion hash), keeps the rest', () => {
    const relaxed = selectorRelaxations(INDEED_BRITTLE);
    assert.equal(
      relaxed[0],
      'div.cardOutline.tapItem.dd-privacy-allow.result.maybeSponsoredJob.resultWithShelf' +
        '.sponTapItem.desktop.hasSection.hasSection-rjpOnSerp.hasSection-extraTier' +
        '.recommendation-section.vjs-highlight',
      'auto-gen-strip is the most-specific (first) candidate; job_ee158ac0af90ece8 + eu4oa1w0 dropped',
    );
    assert.ok(!relaxed[0].includes('job_ee158ac0af90ece8'));
    assert.ok(!relaxed[0].includes('eu4oa1w0'));
  });

  it('the truncation tail (after the auto-gen strip at [0]) shrinks monotonically', () => {
    // [0] is the auto-gen strip (drops hashes, keeps state classes) — it may carry FEWER classes
    // than the first pure truncation, so monotonicity is asserted over the truncation tail [1..].
    const relaxed = selectorRelaxations(INDEED_BRITTLE);
    const tail = relaxed.slice(1).map(s => (s.match(/\./g) || []).length);
    for (let i = 1; i < tail.length; i++) {
      assert.ok(tail[i] < tail[i - 1], `truncation ${i} must be strictly less specific than ${i - 1}`);
    }
    // Every relaxation is less specific than the (failed) original.
    const origCount = (INDEED_BRITTLE.match(/\./g) || []).length;
    for (const s of relaxed) {
      assert.ok((s.match(/\./g) || []).length < origCount, `relaxed sheds at least one class: ${s}`);
    }
  });

  it('never emits the original selector, and never emits duplicates', () => {
    const relaxed = selectorRelaxations(INDEED_BRITTLE);
    assert.ok(!relaxed.includes(INDEED_BRITTLE), 'the (already-failed) exact selector is excluded');
    assert.equal(new Set(relaxed).size, relaxed.length, 'no duplicate relaxations');
  });

  it('preserves the tag and never relaxes below a single class', () => {
    const relaxed = selectorRelaxations(INDEED_BRITTLE);
    for (const s of relaxed) {
      assert.ok(s.startsWith('div.'), `kept the tag: ${s}`);
      assert.ok((s.match(/\./g) || []).length >= 1, `at least one class survives: ${s}`);
    }
    assert.equal(relaxed[relaxed.length - 1], 'div.cardOutline', 'least-specific keeps exactly the first class');
  });
});

describe('selectorRelaxations — preserves meaningful trailing classes via the auto-gen strip', () => {
  it('keeps a semantic trailing class when only a middle token is a hash', () => {
    // `div.result.job_<hash>.title` → .title should SURVIVE; only the key drops.
    const relaxed = selectorRelaxations('div.result.job_070d04fc4355bc03.title');
    assert.equal(relaxed[0], 'div.result.title', 'auto-gen strip preserves .title, drops the job_<hash> key');
  });
});

describe('selectorRelaxations — refuses to relax deliberate anchors', () => {
  it('returns [] for an #id selector', () => {
    assert.deepEqual(selectorRelaxations('#results'), []);
    assert.deepEqual(selectorRelaxations('div#main.foo.bar'), [], 'id present → an intentional anchor, leave alone');
  });
  it('returns [] for an attribute / pseudo / functional final segment', () => {
    assert.deepEqual(selectorRelaxations('input[name="q"]'), []);
    assert.deepEqual(selectorRelaxations('div.card:nth-of-type(2)'), []);
    assert.deepEqual(selectorRelaxations('li:first-child'), []);
  });
  it('returns [] when there is nothing to relax (≤1 class, or empty/garbage)', () => {
    assert.deepEqual(selectorRelaxations('div.cardOutline'), [], 'single class — already minimal');
    assert.deepEqual(selectorRelaxations('.onlyclass'), []);
    assert.deepEqual(selectorRelaxations(''), []);
    assert.deepEqual(selectorRelaxations(null), []);
    assert.deepEqual(selectorRelaxations('   '), []);
  });
});

describe('selectorRelaxations — relaxes the FINAL segment only, prefix untouched', () => {
  it('keeps an ancestor/combinator prefix verbatim', () => {
    const relaxed = selectorRelaxations('main#root > ul.list li.row.is-active.css-1ab2c3d');
    assert.ok(relaxed.length > 0);
    for (const s of relaxed) {
      assert.ok(s.startsWith('main#root > ul.list li.'), `prefix preserved: ${s}`);
    }
    assert.equal(relaxed[0], 'main#root > ul.list li.row.is-active', 'css-1ab2c3d emotion hash dropped first');
  });

  it('caps the number of relaxations at `max`', () => {
    const many = 'div.' + Array.from({ length: 40 }, (_, i) => `c${i}`).join('.');
    assert.ok(selectorRelaxations(many, { max: 5 }).length <= 5);
  });
});

describe('isStableIdent — Indeed durable base classes', () => {
  it('treats the base classes as stable', () => {
    for (const c of ['cardOutline', 'tapItem', 'result']) {
      assert.equal(isStableIdent(c), true, `${c} is a stable ident`);
    }
  });
});
